Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [149]:
import numpy as np

In [151]:
def mat(ip_mat, n, increasing=False):
    if not increasing:
        op_mat=np.array([x**(n-1-i) for x in ip_mat for i in range(n)]).reshape(ip_mat.size, n)
    elif increasing:
        op_mat= np.array([x**i for x in ip_mat for i in range(n)]).reshape(ip_mat.size,n)
    return op_mat
ip_mat= np.array([1,2,3,4])
n=3
print("descending order")
print(mat(ip_mat,n, False))
print("ascending order")
print(mat(ip_mat,n, True))

descending order
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
ascending order
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [152]:
def moving_avg(a,n=3):
    sum = np.cumsum(a,dtype=float)
    sum[n:] = sum[n:] - sum[:-n]
    return sum[n - 1:] / n
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_avg(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
